### PR TITLE
Add 16px and 32px favicon

### PR DESCRIPTION
**Pull request by SheldonCheng**
As per title.

image

### CODE REVIEW

**Review by jacobtyq — COMMENTED** [review]
I can't test this as the favicons are not displaying on my machine, however can see that go-gin is returning status 200 on both `favicon-32x32` and `favicon-16x16`.

@subhransu could you try?

**Comment by subhransu** [comment]
Can't see this as well. 

## On Chrome (the default icon gets displayed) 
Screenshot 2020-12-01 at 3 40 34 PM

## On Safari (Somehow Google icon is getting displayed)
Screenshot 2020-12-01 at 3 40 23 PM

Do we need to set `PUBLIC_URL` environment variable somewhere?

**Comment by SheldonCheng** [comment]
Oh I didn't realise the default favicon wasn't working also.
I tested again in server mode and I get the same problem. Let me check.

**Comment by SheldonCheng** [comment]
Ok I think I know what's wrong.

Router at `main.go` is configured to return `index.html` for any request to root `/`.
So `localhost:8080/favicon.png` returns a text/html and not the actual asset in `dist` folder.

Only requests to `/static` are actually retrieved from the /static folder.

With this knowledge, I have created a subfolder in /public, and moved the favicons there. So on build:
`public/static/favicon.png` -> `dist/static/favicon.png`.
Since it is now copied into the special static folder on build, it is now retrievable.

While this works now, I think it's probably not the right way, since some files like `robot.txt` are missed. Shouldn't the server try check presence of the file before falling back to index.html? @subhransu

**Comment by subhransu** [comment]
Let me check how to do with gincotext. The URLs routes should be handled properly on the server.
So if your initial implementation is correct, I need to modify the routes or add the check.

**Comment by subhransu** [comment]
@SheldonCheng I checked how to do it in gin. They recommend using `.ico` files instead of `.png`
Should we be using `.ico` files as well? 

The router still needs some modifications to support this. 

Sample from [this source](https://libraries.io/go/github.com%2Fgin-gonic%2Fgin%2Fexamples%2Ffavicon):
```
func main() {
	router := gin.Default()
	router.Static("/assets", "./assets")
	router.StaticFS("/more_static", http.Dir("my_file_system"))
	router.StaticFile("/favicon.ico", "./resources/favicon.ico")

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```

**Comment by jacobtyq** [comment]
> @SheldonCheng I checked how to do it in gin. They recommend using `.ico` files instead of `.png`
> Should we be using `.ico` files as well?
> 
> The router still needs some modifications to support this.
> 
> Sample from [this source](https://libraries.io/go/github.com%2Fgin-gonic%2Fgin%2Fexamples%2Ffavicon):
> 
> ```
> func main() {
> 	router := gin.Default()
> 	router.Static("/assets", "./assets")
> 	router.StaticFS("/more_static", http.Dir("my_file_system"))
> 	router.StaticFile("/favicon.ico", "./resources/favicon.ico")
> 
> 	// Listen and serve on 0.0.0.0:8080
> 	router.Run(":8080")
> }
> ```

Seems like using a mixture of .ico and .png would be better according to this https://stackoverflow.com/a/48969053

**Comment by SheldonCheng** [comment]
Ok I've added favicon.ico as well.

**Review by subhransu — APPROVED** [review]

**Pull request merged**
