### PR TITLE
Integrate with auth0 and linked in

### PR DESCRIPTION
**Pull request by kajalsinha**
I need a react+ts expert to convert js to tsx. thx

### CODE REVIEW

**Comment by subhransu** [comment]
@lxcid @SheldonCheng can help with the ReactJS stuff?

**Comment by lxcid** [comment]
Will take over and do it today.

**Comment by lxcid** [comment]
I just look at it, probably needed more time for it.

**Comment by lxcid** [comment]
I'm able to authorise but when I subsequently return (e.g. refresh the page), somehow, the authentication system keep throwing 400, causing Auth0 SDK to get suck.

If you invite me to Auth0 maybe I can fix it.

Screen Shot 2020-05-24 at 1 21 07 PM

**Comment by subhransu** [comment]
@lxcid have invited you to Auth0

**Comment by lxcid** [comment]
This should be ready, do take note that I have introduce `REACT_APP_URL` environment variable to identify the URL of the website, this is use for composing the 0auth redirect url.

Also do take note that the URL are white listed so if we supporting/deploying new domain, they have to be deployed to production and update the whitelist

from auth0 and our system point of view, I think we are authenticated, but I'm not sure do we need to inform the server that we are authenticated? So while I can get auth0 to recognise me, I'm not sure what to do next.

but afaik, this PR is ready.

**Review by ivanfoong — APPROVED** [review]

**Pull request merged**
