### PR TITLE
Send Authorization Bearer Token if available during API request

### PR DESCRIPTION
**Pull request by lxcid**

### CODE REVIEW

**Comment by lxcid** [comment]
I have created our own API Client and add the bearer token there. This is such that we don't accidentally send the token to another website if we happen to use the global axios API.

Otherwise, I have delayed the request until it is ready to send so that the API request will have the bearer token.

**Comment by subhransu** [comment]
@lxcid @SheldonCheng there seem to be some conflicts. Please help to resolve these.

**Review by SheldonCheng — APPROVED** [review]

**Comment by SheldonCheng** [comment]
@lxcid I've merged master and updated `useJobsReducer` and `useTalentsReducer` to use your `JobsGoWhereApiClient`.
Just to clarify, this branch requires user to be authenticated to request jobs/talents right?

**Comment by lxcid** [comment]
@SheldonCheng hey man! Sorry I missed yesterday call.

if I'm not wrong, this branch only wait until we know if the user is authenticate or not before sending the request.

This is so that we can attach authentication header, as there is a delay from initialising the auth0 to actually knowing whether the user is authenticated or not.

Unauthenticated user can still send the request, just that they will not have the headers.

**Comment by subhransu** [comment]
Let's hold then, I send the PR for profile API Today.

**Pull request merged**
